### ISSUE TITLE
Lava priv is "unknown"

### ISSUE THREAD

**Issue by ragulanramkumar** [obl3pplifp/BlS-issue-tracker#101]
Title, the lava priv cannot be granted

Peat and Superuser have requested the priv, so once this has been fixed if it could be granted that would be great.

**Comment by fluxionary** [comment]
Someone crashed the server while I was consolidating this change into the "bls_custom" mod, and I hadn't pulled the update yet. Should work after the next reboot.

**Comment by fluxionary** [comment]
Works, and privs granted.
