### ISSUE TITLE
newly placed moreblocks:empty_shelf nodes can't be accessed anymore

### ISSUE THREAD

**Issue by ragulanramkumar** [obl3pplifp/BlS-issue-tracker#102]

**Comment by fluxionary** [comment]
This might be related to an update to xdecor a couple days ago, where now the xdecor shelf is overridden by the moreblocks one. Certainly, that has messed up the crafting recipes. I need to figure out why the moreblocks empty shelf is no longer treated like an inventory, though

**Comment by fluxionary** [comment]
Or maybe the moreblocks empty shelf never was an inventory, and ones that have an inventory used to be xdecor empty shelves...

**Comment by fluxionary** [comment]
So, the xdecor shelves had inventories, and i guess ones that were placed and were converted to moreblocks shelves now have inventories... But moreblocks shelves never had inventories, so newly placed ones won't either. I'm not even sure this is really a bug...

**Comment by fluxionary** [comment]
Empty shelves are craftable again, but I'm not going to "fix" the issue that they are no longer inventories.
