### ISSUE TITLE
Fix "Craft All" button in unified_inventory

### ISSUE THREAD

**Issue by fluxionary** [obl3pplifp/BlS-issue-tracker#103]
It went from 1 stupid behaviour to another.

**Comment by fluxionary** [comment]
... what? Remind myself to figure out what it's doing?

**Comment by WulftheNordicRanger** [comment]
iirc, it distributed items unevenly in the craft grid

**Comment by fluxionary** [comment]
Oh, right, that's what this is about; not the button in `unified_inventory_plus` that crafts everything in your crafting grid. The original stupid behaviour was that it added every item to the inventory *one at a time* instead of moving things in bulk. The stupid fix was to make it move things *ten at a time*. Currently, I think it does the right thing, so I'm closing this.
