### ISSUE TITLE
Server staff should be able to access locked travelnets

### ISSUE THREAD

**Issue by ragulanramkumar** [obl3pplifp/BlS-issue-tracker#110]
Title

**Comment by fluxionary** [comment]
@xerox123official They can, you just need to be holding a keyring. Slightly annoying, and maybe it should be set up so that it doesn't require one. Thoughts?

**Comment by fluxionary** [comment]
Fixed (pending reboot) by moving the check for the existing `openlocks` priv above the keychain check.
