### ISSUE TITLE
Unified Inventory Plus

### ISSUE THREAD

**Issue by fluxionary** [obl3pplifp/BlS-issue-tracker#113]
But first we'd have to fix the issues w.r.t bulk crafting and stamina

**Comment by fluxionary** [comment]
Once my API update to the stamina mod gets accepted, this can be fixed.

**Comment by fluxionary** [comment]
The stamina API exists, just have to get to updating this mod...

**Comment by thomasrudin** [comment]
Just a heads-up: the coloring of items does not work with the "Craft All" button:
https://github.com/bousket/unified_inventory_plus/blob/master/init.lua#L40

**Comment by fluxionary** [comment]
Made the stamina change, added the mod to our server (currently pointed to my fork, but will fix that when the PR gets accepted).

@thomasrudin I see, you mean the colouring of items through the unifieddyes API doesn't work. Interesting. I expect that could be fixed if someone requests it.
