### ISSUE TITLE
Ensure every interface where a player can write things is logged

### ISSUE THREAD

**Issue by fluxionary** [obl3pplifp/BlS-issue-tracker#120]
Players understand that chat is logged and PMs are logged. I've written some code to ensure that letters (from memorandum) are logged, signs are logged (only the two basic signs already were), and books are logged (books from homedecor were already logged). However, there's several other blocks where players can write things e.g. digiline channels, lua controllers, ...

Possibly incomplete list of places where text can be input:
- [x] Smartshop wifi storage names
- [x] signs from the display modpack
- [x] default books (via monkey patching)
- [x] homedecor books
- [ ] Technics chest descriptions
- [x] lua controllers
- [ ] channel names in all digilines-capable nodes
  - [ ] digilines
  - [ ] digistuff
  - [ ] digiterms
  - [ ] led_marquee
  - [ ] homedecor_lighting
  - [ ] moremesecons_wireless
- [ ] memorandum
- [ ] travelnet and locked_travelnet station names and networks
- [ ] areas (naming areas)
- [ ] moremesecons (craftable) command blocks
- [ ] other moremesecons stuff?

--------------------
Mods that don't matter:
* regular mesecons command blocks (because normal players can't edit them)

**Comment by krypticbit** [comment]
Having luaC text in logs could be a bit spammy, but I suppose it could be useful ...

**Comment by catwhisperer77** [comment]
I assume there you'd log the code, not every instance of lua text triggering?

**Comment by fluxionary** [comment]
cat: It'd be every time the user updated/saved the contents of the lua controller, i.e. when they clicked "execute". Not when it's being executed by other events.

**Comment by wireva** [comment]
Why do you log signs???

**Comment by luk3yx** [comment]
Because malicious players could use them to communicate/threaten regular players or bypass the family-friendly chat rule.

**Comment by fluxionary** [comment]
@Niwla23 specifically, a player who was banned for very serious things was using signs to pass messages to other players, to try to get around the PM snooping.

**Comment by fluxionary** [comment]
At the moment, I've currently got an override that logs every time a user submits anything to a formspec; I'm fairly certain that this covers every mode of communication possible outside of game chat (barring building messages out of individual letters or other things that are too absurd to worry about). While I haven't verified that every mod listed above is logged, I'm confident enough to consider this closed.
