### ISSUE TITLE
Anyone can use locked travelnets if they punch it

### ISSUE THREAD

**Issue by fluxionary** [obl3pplifp/BlS-issue-tracker#121]
This kind of makes them pointless.

**Comment by fluxionary** [comment]
Upstream issue:
https://github.com/Sokomine/locked_travelnet/issues/4

**Comment by fluxionary** [comment]
Sokomine is reportedly overwhelmed w/ issues currently, so one of us will probably have to create the PR.

**Comment by Lanhild** [comment]
Make it act as when you don't have the key nor the code, it acts as if you try to break a block, so it turns player view 180 degrees so you can't use it. ( I don't think this is really possible)

**Comment by oversword** [comment]
Fixed in https://github.com/Sokomine/locked_travelnet/pull/5
@Lanhild unfortunately I don't think it's so easy to do that, it's not the same as the dig callback. I've just made it so nothing happens if a non-owner user punches it
