### ISSUE TITLE
"revert" flower spread rules

### ISSUE THREAD

**Issue by fluxionary** [obl3pplifp/BlS-issue-tracker#124]
Players are unhappy with the fact that flowers don't spread as well as they used to; I can't say I blame them. I want to bring back the old statistics for flower spread.

**Comment by Panquesito7** [comment]
See [495fa32](https://github.com/minetest/minetest_game/commit/495fa32873202c667c589ae691f5e67186762521) for more information.
I guess it is revelant to what you're saying.

**Comment by fluxionary** [comment]
Oh, thanks for the ping, i already implemented this a few days ago. Closing.

**Comment by Panquesito7** [comment]
Okay. Very well!

**Comment by fluxionary** [comment]
Relevant commit in the bls_custom mod: https://github.com/BlockySurvival/bls_custom/commit/93e03ce614b5e36a4b66bc30825ff0987f883c86

**Comment by Panquesito7** [comment]
I see...thought it was from MTG.

**Comment by fluxionary** [comment]
Oh, the default behaviour *is* defined in MTG, but here I'm overriding it. It's the same function, but I've changed `if #minetest.find_nodes_in_area(pos0, pos1, "group:flora") > 3 then` to `if #minetest.find_nodes_in_area(pos0, pos1, "group:flora") > 7 then`

**Comment by Panquesito7** [comment]
Very well! 👍
