### ISSUE TITLE
Analyze and possibly resolve spawn "lag"

### ISSUE THREAD

**Issue by fluxionary** [obl3pplifp/BlS-issue-tracker#125]
Hello @SmallJoker,

I know you've run some performance tests on our sever before, and I was wondering if you could give me any insight (or directions on how to acquire insight) into why the spawn area on BlockySurvival is so "laggy" (using the parlance of our userbase; they mean they get low FPS). We've tried a number of things - removing the animals from the area, removing (most) plants from the area, removing (most) shops from the area, removing machines from the area, and still it remains far laggier than many other areas if the server.

If you don't want to do this or don't have the time, just let me know, and I'll keep poking at it on my own.

**Comment by SmallJoker** [comment]
![image](https://user-images.githubusercontent.com/1497498/62422199-f1df0380-b6ae-11e9-862a-d56d9646ac33.png)
200k solid vertices

![image](https://user-images.githubusercontent.com/1497498/62422220-1f2bb180-b6af-11e9-9c41-a2a509b8d1e6.png)
17k transparent vertices

Outside from spawn there's about 1/10 of the solid vertices and a few hundred of transparent ones. The real bottleneck however seem to be the 27 animated meshes at spawn - maybe it's the chimney smoke? I don't know.

**Comment by fluxionary** [comment]
Might the animated meshes be the animals? I removed the chimney smoke, but that was only 16 nodes. I'm not sure what other things like that smoke there are around.

Is there a way I can get stats like that to show up in my local client? Building in debug mode didn't do anything magical in that regard.

**Comment by SmallJoker** [comment]
Any client build, hit F6 two or three times.
EDIT: Animated meshes are from ClientMap, so it's very likely it's just the animated nodes.

**Comment by fluxionary** [comment]
Right. I've always had F6 bound to turn my music on/off so i never even noticed that function. I'm pretty sure the animated meshes are just torches - do you really thing those are causing an issue? I'm leaning more towards smartshops that are a bit farther from spawn, and maybe microblocks (stairs etc).

**Comment by SmallJoker** [comment]
I cannot tell the real source of this problem either (yet). But I believe something keeps refreshing the mapblock meshes, which takes a while.

**Comment by fluxionary** [comment]
![deepin-screen-recorder_Minetest_20190817112546](https://user-images.githubusercontent.com/25628292/63211059-d4179280-c0e1-11e9-9b8f-df5bca0b7290.gif)

I *really* feel like there's something very wrong w/ how occlusion culling is working. like, it's barely working at all.

**Comment by SmallJoker** [comment]
Does https://github.com/minetest/minetest/pull/8812 help?

**Comment by fluxionary** [comment]
![deepin-screen-recorder_Minetest_20190817150328](https://user-images.githubusercontent.com/25628292/63213863-cf160b80-c100-11e9-91ce-b6807a2dcc9e.gif)

This is just w/ an updated client; I can't update the server myself, though I can bug the appropriate parties if that's necessary. There's *definitely* a lot more area that's blinking now than I noticed not rendering in wireframe mode before. However, frame rate seems entirely unchanged. 

@SmallJoker also, I've given you fly, noclip and debug privs on the server if you want to poke at it more yourself.

**Comment by SmallJoker** [comment]
Meanwhile I downloaded the spawn area to my disk for faster local testing (3s join vs 30s). Thanks for the privileges., even if `debug` alone would already be enough to test the occlusion culling stuff.

**Comment by fluxionary** [comment]
Probably faster to start it w/out all the mods, but if you want to replicate what we have on the server, you can use https://github.com/BlockySurvival/bls_mods.git

**Comment by lhofhansl** [comment]
Please keep in mind with this, that the server also performs occlusion culling, and hence does not send blocks that are culled in the first place. Unless you move around and look at the map from the different angles the client would indeed not cull any additional blocks (hence 0 is not necessarily bad).

@SmallJoker

**Comment by SmallJoker** [comment]
@lhofhansl 
1) I explored the spawn a bit
2) Much air, less light-blocking nodes
3) The mapblocks outside of the FOV-range aren't occlusion culled either

I know how this ought to work. The wireframe mode showed that it's really not working properly in some cases.

**Comment by fluxionary** [comment]
Some updates:
1) Changing the draw type of smartshop's entities reduced FPS "lag" noticably.
2) Futureismine removing all of his hundreds of shops from near spawn reduced FPS "lag" tremendously. 

I still have noticeably lower FPS at spawn than a lot of other parts of the server (including areas w/ big, complicated buildings). I still think the broken culling is having an impact - all the buildings made of many different materials, as well as all the "noob tube"-type mineshafts that are hidden underground.

**Comment by fluxionary** [comment]
Other things that were done:
1. uninstall signs_lib; it made the signs even laggier
2. despawn all the nsspf fungi
3. set `active_object_send_range_blocks` to 1

These changes have all noticeably decreased the drawing time and load time of spawn and other busy areas.  I'm considering this issue solved at the moment.
