### ISSUE TITLE
Mod request: Kill Button

### ISSUE THREAD

**Issue by wireva** [obl3pplifp/BlS-issue-tracker#134]
https://gitlab.com/Niwla23/killbutton/

**Comment by ragulanramkumar** [comment]
Don't know if I'm being pedantic here, but I don't think it's a good idea to name it 'KILL YOURSELF'.

Maybe calling it a respawn button would be better?

**Comment by fluxionary** [comment]
@Niwla23 I also already asked for you to not name it "KILL YOURSELF!". It feels like it's celebrating suicide that way.

**Comment by luk3yx** [comment]
Wouldn't it be better to make a `/spawn` button?

**Comment by fluxionary** [comment]
Yeah, maybe the more I think about this, the more I think it doesn't really add anything.

**Comment by wireva** [comment]
https://gitlab.com/Niwla23/killbutton/commit/ba5e2e07a7779a9f426bac1bb32436ed0beb47d7

**Comment by wireva** [comment]
> @Niwla23 I also already asked for you to not name it "KILL YOURSELF!". It feels like it's celebrating suicide that way.

HAvent seen that

**Comment by fluxionary** [comment]
It's installed, but I'm still not sure I'm happy with it. At least one player has already accidentally killed themselves with it.

**Comment by luk3yx** [comment]
This mod sets the global variable `name`, this looks like a bug.

**Comment by fluxionary** [comment]
I've only heard the one complaint so far, so I'm leaving it in and closing this. 

@Niwla23 Please fix the issue w/ the undeclared global variable (just put "local" before it). Also, it would be nice if the mod detected if the player was wearing armour, and if so, warn them that it will drop their armour when they die.
