### ISSUE TITLE
Everyone can configure delayers in protected areas

### ISSUE THREAD

**Issue by wireva** [obl3pplifp/BlS-issue-tracker#153]
the delay of mesecons delayers can be set by anyone in protected areas.

Also, maybe add locked mese stuff? Like locked buttons or switches

**Comment by fluxionary** [comment]
You could file this issue upstream. I'm unlikely to get to it anytime soon.

**Comment by wireva** [comment]
> You could file this issue upstream.

What means upstream?

**Comment by fluxionary** [comment]
https://github.com/minetest-mods/mesecons/issues/new

**Comment by fluxionary** [comment]
The locked button is actually a nice request. i know that exists, let me figure out what mod it's from.

**Comment by wireva** [comment]
ok, i put the issue on meseons

**Comment by luk3yx** [comment]
https://github.com/minetest-mods/mesecons/issues/488

**Comment by thomasrudin** [comment]
> The locked button is actually a nice request. i know that exists, let me figure out what mod it's from.

https://github.com/pandorabox-io/mesecons_protected_switch

https://github.com/pandorabox-io/mesecons_protected_button

**Comment by luk3yx** [comment]
This was fixed in https://github.com/minetest-mods/mesecons/pull/490.
