### ISSUE TITLE
Some microblocks are unknown nodes since 5.1 update.

### ISSUE THREAD

**Issue by luk3yx** [obl3pplifp/BlS-issue-tracker#154]
```
<flux> bunch of microblocks that were made w/ the xdecor workbench are now unknown nodes
```

Unknown nodes that I know of:

 - `stairs:stair_white`
 - `stairs:slab_white`
 - `stairs:stair_block`
 - `stairs:slab_chiseled`

**Comment by fluxionary** [comment]
"block" and "chiseled" are from the quartz mod.

The following blocks from the following mods are affected, and I already tried to fix them, but for some reason `register_alias_force` isn't working:

* bakedclay (all variants including natural)
* quartz: 3 block variants
* bridger: 3 colored block variants
* nether: rack and brick (maybe enchanted obsidian?)
* building_blocks: all blocks (hardwood, adobe, etc)
* cblocks: all variants

the following types of microblocks are affected:
* slab
* stair
* stair_inner
* stair_outer

I aliased all the affected blocks to their circular saw equivalents, but exactly *nothing* changed.

**Comment by fluxionary** [comment]
My assumption that the xdecor workbench is involved is based on the state of the pool at the top of Blossum2k9's hotel. When I built that, coloured glass wasn't cut-able in the circular saw, and I very much remember that the resulting blocks were no longer transparent (which actually looked quite nice).

**Comment by fluxionary** [comment]
unknown nodes from microblock SNAFU should now be resolved. if i've missed something, please open another issue.
