### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by 6nop6nop** [obl3pplifp/BlS-issue-tracker#157]
<img width="880" alt="Screen Shot 2019-10-26 at 10 58 57 AM" src="https://user-images.githubusercontent.com/56689293/67623246-2e1e8d80-f7e0-11e9-8a91-f56825923fe5.png">

**Comment by fluxionary** [comment]
@6nop6nop I can't replicate this issue. I placed down a HT furnace in a private world, put in the same upgrades, filled it with potatoes, and supplied heat. Potatoes are cooking and ending up in the inventory. Can you supply more details?

**Comment by 6nop6nop** [comment]
nvm it started working when i removed the potatoes and then put them back
