### ISSUE TITLE
unified inventory (or unified inventory plus) does insane things when crafting items with replacements

### ISSUE THREAD

**Issue by fluxionary** [obl3pplifp/BlS-issue-tracker#166]
1. if you hit the "All" button to craft things, you will only get 1 side effect item, no matter how many items you craft.
2. ~~if you craft something that has multiple side effects (like cucina vegana's rice flour), when *not* using the "All" button, you get way too many items back (probably 2x, didn't count)~~

**Comment by catwhisperer77** [comment]
For the rice flour, is that something to do with how it's [replacing the first stone with 3 stones](https://github.com/acmgit/cucina_vegana/blob/5d92dedd6d1adb0f1f5ce32fc927cd57fce275eb/recipes.lua#L187)?

**Comment by fluxionary** [comment]
ah. nice catch. its replacing each of 3 stones w/ 3 stones. so only point 1 is valid, and cucina vegana needs its own fix.

**Comment by catwhisperer77** [comment]
homedecor dye-ables (beds/glowlights) fail to craft when using the all button (it consumes the dye and makes the default/white version)

**Comment by fluxionary** [comment]
Related upstream issues / PRs
* [ ] https://github.com/minetest/minetest/issues/9250
* [x] https://github.com/acmgit/cucina_vegana/pull/3
* [ ] https://github.com/bousket/unified_inventory_plus/issues/6

**Comment by fluxionary** [comment]
This issue is still unresolved upstream. We may have to take it over.

**Comment by fluxionary** [comment]
I rewrote unified_inventory_plus, and fixed all of the major issues:
https://github.com/bousket/unified_inventory_plus/pull/16
bousket doesn't want to actively maintain the mod anymore, so if I don't hear back from them, I'm going to try to get the mod moved into minetest-mods. 

@oversword: feel free to point at my repo for the time being, if you wish.
