### ISSUE TITLE
Warehouse Duplication

### ISSUE THREAD

**Issue by oversword** [obl3pplifp/BlS-issue-tracker#168]
Warehouses, specifically gold warehouses (techpack) can be used to duplicate items infinitely (so long as you have at least 3 items)

To replicate:

1. Place a warehouse and collect 3 of the same item.
2. Use one of the items to configure the fist slot of the warehouse (left-right)
3. Put the other 2 items in the warehouse and let them find their slot
4. Pick up the 2 items and scroll up and down quickly
5. You should now have 4 items in your inventory
6. Rinse and repeat to duplicate infinitely

- This bug depends on the speed you scroll
- The normal scrolling behaviour is to put items from the stack in your inventory one by one
- The warehouse overrides this behaviour to put a full stack on each scroll (if possible)
- This has already been fixed (submitting immanently) by getting the `main_stack` from the `node_inv` each time `move_to_player_inv` is called instead of passing it in

**Comment by oversword** [comment]
Also: flux, what's going on with the server? ?? ?? ??

**Comment by oversword** [comment]
I was having isues upgrading this with the instructions on the mods repo, I've submitted a a change to techpack, please pull!
Or see my fork https://github.com/oversword/techpack

Pull request on techpack: https://github.com/joe7575/techpack/pull/43
Issue on techpack: https://github.com/joe7575/techpack/issues/42

**Comment by fluxionary** [comment]
Thanks Oversword, I'll try to pull this into our techpack repo after reviewing it. 

RE: the server, we switched hosts for the server and had some DNS SNAFU, so it took a little while for the public server listing to work again.

**Comment by luk3yx** [comment]
The upstream PR has been merged, is there anything needing to be done before this is closed?

**Comment by oversword** [comment]
Nope, will close. Thanks @luk3yx
