### ISSUE TITLE
Vegan leather

### ISSUE THREAD

**Issue by catwhisperer77** [obl3pplifp/BlS-issue-tracker#169]
We've already added a bunch of ways to make vegan meat alternatives from tofu - given the importance of leather in quite a few crafting recipes, maybe there should be an alternative way to get it other than hunting mobs?

(It'll reduce the cost of leather currently, but it could be costly, like several plastic and dye in an alloy smelter)

**Comment by fluxionary** [comment]
![Naugahyde-large](https://user-images.githubusercontent.com/25628292/71756700-07886d00-2e89-11ea-9101-115f36ae9401.jpg)

**Comment by fluxionary** [comment]
i like the idea, but currently leather is only used in recipes for things that i want to be quite hard to make, so vegan leather should be maybe equally hard, but more automatable. i'll think about ways to do that, suggestions are welcome.

**Comment by TechDudie** [comment]
I have added artificial leather in my mod.

**Comment by oversword** [comment]
Kiko suggests: so wool top row, parafin middle row, flax bottom row

```
Wool          wool          wool
parafin       parafin       parafin
cooked flax   cooked flax   cooked flax
>
1 leather
```

I think the complexity of the craft makes it non-OP

**Comment by oversword** [comment]
Correction: the idea was to use 9 of each item in each slot, which cannot work, an intermediate step has been suggested.

I don't think it is necessary, but maybe the recipe stated above is a little too easy
