### ISSUE TITLE
Wireless mesecons can replace existing nodes

### ISSUE THREAD

**Issue by luk3yx** [obl3pplifp/BlS-issue-tracker#170]
If a wireless mesecon gets removed without an `on_destruct` call (such as with WorldEdit), when triggered the node will reappear without any apparent way to permanently remove it.

A check to ensure that the target node is indeed a wireless mesecon should be added near https://github.com/minetest-mods/MoreMesecons/blob/master/moremesecons_wireless/init.lua#L183, and if it isn't the position should be removed from the list.

**Comment by luk3yx** [comment]
This should be fixed after the next mod update, the bugfix is available at https://github.com/BlockySurvival/MoreMesecons.

**Comment by fluxionary** [comment]
the update is installed, i never really poked around w/ wireless mesecons, and haven't verified the resolution.
