### ISSUE TITLE
Empty water_bucket group?

### ISSUE THREAD

**Issue by akozlovskiy119** [obl3pplifp/BlS-issue-tracker#177]
Crafting guide shows nothing when I search for `group:water_bucket`. I expect it to show at least the default water bucket and the river water bucket as it is in the default `minetest_game`.

`moreblocks:copperpatina` recipe depends on this group, and therefore is uncraftable.

**Comment by fluxionary** [comment]
Thanks for reporting this, I'll look into it.

**Comment by fluxionary** [comment]
Apparently it's the BBQ mod that's overriding the groups for buckets. I filed a PR upstream:
* https://github.com/Grizzly-Adam/BBQ/pull/6/files

I'll add a shim to fix the issue in the meantime.

**Comment by akozlovskiy119** [comment]
Woah, that was fast! Thank you for fixing this.

**Comment by fluxionary** [comment]
The shim is in place, though it won't take effect  until the next server reboot, which will be within the week.

**Comment by fluxionary** [comment]
as an aside:
i responded to this quickly only cuz it was easy enough that i was up for it. i'll respond to most things within a day or two, but rarely this quickly =b

**Comment by luk3yx** [comment]
Live-patched the server, this should no longer be an issue.
