### ISSUE TITLE
Figure out why the server hangs recently

### ISSUE THREAD

**Issue by fluxionary** [obl3pplifp/BlS-issue-tracker#180]
The server has hung 3 or 4 times in the last few weeks. The process is still running, but does not accept new connections or send packets to any clients. Everyone times out, and nothing new is written to the logs, which makes me think it's stuck in an infinite loop somewhere. The CPU is pegged @ 100% (1 thread). The RAM is high, but that's likely just because we never solved that other memory leak issue (though it isn't horrible anymore)

It would be useful to analyze if these crashes happen at a certain time of day or when certain players are connected.

**Comment by BuckarooBanzay** [comment]
This sounds a lot like this:
https://github.com/minetest/minetest/pull/9350

I've mitigated that in our `custom` repo:
```lua
local actual_unpack = unpack
function unpack(t, a, b)
	assert(not b or b < 2^30)
	return actual_unpack(t, a, b)
end
```

https://github.com/pandorabox-io/pandorabox_custom/blob/cf894e0707ab3bf45dc53b0519e0602951dd3325/hacks.lua#L13-L17

**Comment by fluxionary** [comment]
Thanks Buckaroo, it does sound possible. We also have had some hard crashes w/out any sort of error message recently, which also sounds like it could be this issue? But this would have to be done by a malicious player fiddling w/ a luacontroller, right?

**Comment by BuckarooBanzay** [comment]
> But this would have to be done by a malicious player fiddling w/ a luacontroller, right?

Yes, but there won't be any log-message about where/who though... :disappointed:

**Comment by fluxionary** [comment]
I added that "fix" to unpack and put in some code to log the contents of luacontrollers (which I've wanted for a while for Other Reasons). I suppose now we wait and see what happens.

**Comment by fluxionary** [comment]
weird hangs haven't been an issue in a long time, i don't think
