### ISSUE TITLE
moretrees don't respect protection when they grow

### ISSUE THREAD

**Issue by fluxionary** [obl3pplifp/BlS-issue-tracker#187]
This has been known for a while, but someone else reported it, so recording it here (for when I get around to fixing stuff again).

**Comment by Panquesito7** [comment]
Submitted a [**pull request**](https://gitlab.com/VanessaE/moretrees/-/merge_requests/6) to fix this.

**Comment by fluxionary** [comment]
Thank you! I'll watch that PR (MR on gitlab)

**Comment by fluxionary** [comment]
This should be in place. Thanks again @Panquesito7!

**Comment by oversword** [comment]
This is fixed and working on the server
