### ISSUE TITLE
Digiprinter bugs

### ISSUE THREAD

**Issue by fluxionary** [obl3pplifp/BlS-issue-tracker#195]
Per Blackrabbit
```
creo que la digiline printer esta bugeada, no larga el papel y no puedo retirala del piso
```

per google translate
```
I think the digiline printer is buggy, it does not cut the paper and I cannot remove it from the floor
```

**Comment by oversword** [comment]
The only issue I see is that paper cannot be removed from an idle printer... I feel this is probably supposed to be the other way around, it makes sense if you can't remove it from a busy printer, but making it stay in the idle printer means the printer cannot be removed while idle
