### ISSUE TITLE
Artificial Hives do not respect Protection

### ISSUE THREAD

**Issue by DefaultSobriquet** [obl3pplifp/BlS-issue-tracker#199]
While wandering around a honey farm, I found I was able to remove honey from artificial hives, even though the area was protected by other players. 

I assume this behavior is not intentional and should probably be patched at some point as to prevent players from gaining any (sweet) pilfering opportunities. 

![image](https://user-images.githubusercontent.com/51099220/81622295-716bd280-93a5-11ea-8070-e981ddead1b3.png)

**Comment by TechDudie** [comment]
Just solve this problem by building a room around the honey farm.

**Comment by oversword** [comment]
Fixed in https://github.com/minetest-mods/xdecor/pull/138

**Comment by oversword** [comment]
This fix has been rejected upstream, let me know if we still want this

**Comment by fluxionary** [comment]
literally one of my first memories of this server was pulling honey out of an unprotected hive (i forget the player's name. it was very close to spawn. agura destroyed his builds and those of several nearby players, and then built a rather nice facade of a house over it). it's got history and a little charm, if you want to provide some free food for passing newbs.

on the other hand, nearly every other storage is either locked or protected, and that's often the expectation. it could be griefing? but quite a small one. honey isn't very valuable, and it's easy to protect your honey farm if you want to. 

so i could go either way about using this fix.
