### ISSUE TITLE
Players can place blocks over the upper half of travelnets

### ISSUE THREAD

**Issue by fluxionary** [obl3pplifp/BlS-issue-tracker#204]
The solution is probably to write a `minetest.register_on_placenode` callback that does the appropriate checks and prevents this. Probably best if it can be PR'ed into the Sokomine's repo even if we're using our own fork. 

![screenshot_20200517_183759](https://user-images.githubusercontent.com/25628292/82156987-40d8dc80-986e-11ea-9dbc-b48da591f04e.png)

**Comment by fluxionary** [comment]
Upstream: https://github.com/Sokomine/travelnet/issues/55

**Comment by wsor4035** [comment]
see https://github.com/pandorabox-io/pandorabox.io/issues/337 issue on same subject where it was solved in https://github.com/mt-mods/travelnet fork

**Comment by oversword** [comment]
Petition to add the "ugh" tag :P

**Comment by oversword** [comment]
The fix mentioned in the mt-mods fork uses a new `travelnet:hidden_top` node in a similar way to how doors solve the same problem. I will use this method to fix the issue.

**Comment by oversword** [comment]
I've fixed this for travelnets, locked_travelnets and elevators.
This will only affect newly placed nodes though, any ideas on the best way to fix existing nodes?

Edit: register_on_placenode does not seem to be doing anything useful, returning true false or nil does not stop the block being placed
