### ISSUE TITLE
sakuragi & redtree saplings grow into trees no matter what they are placed on, and not just (some subset of) group:soil

### ISSUE THREAD

**Issue by fluxionary** [obl3pplifp/BlS-issue-tracker#207]
They shouldn't. I suspect the issue is in biome_lib, and might be an LBM.

**Comment by fluxionary** [comment]
Also redtrees. And they grow on any node, not just the pots.

**Comment by oversword** [comment]
Fixed in https://github.com/BlockySurvival/redtrees/pull/2

**Comment by oversword** [comment]
Whoops, I made a mistake and declared the new functions as globals, will need another PR to fix this

**Comment by oversword** [comment]
Please pull this asap https://github.com/BlockySurvival/redtrees/pull/3

the current code is erroneous
