### ISSUE TITLE
protected steel door unable to close

### ISSUE THREAD

**Issue by ViniProTheBro** [obl3pplifp/BlS-issue-tracker#216]
cant close protected steel door without areas priv? not to sure.

**Comment by fluxionary** [comment]
@ViniProTheBro I can't replicate this (as flux, in my own area, w/ all privs except `areas`). Can you give some more details?

**Comment by fluxionary** [comment]
FrostRanger verified for me that this is a real issue rn. It's most likely due to an update to minetest_game's `doors` mod; I pulled in updates to that recently (as it's basically declared "stable" rn). It's possibly due to the fact that there's multiple owners on the area.

**Comment by fluxionary** [comment]
FR relays that this happens even in areas that only one player owns, and in unprotected areas. Very weird.

**Comment by fluxionary** [comment]
It was due to this change:

https://github.com/minetest/minetest_game/commit/189d2d9fb1ac6491eb094314fcd6daa753480263#diff-82ce76da0c47bb1b6754e4277adb052a

It's fixed now, but not yet live.

**Comment by fluxionary** [comment]
Fixed & Live
