### ISSUE TITLE
Players start suffocating when they really shouldn't

### ISSUE THREAD

**Issue by WulftheNordicRanger** [obl3pplifp/BlS-issue-tracker#217]
Players start losing air when they stand next to blocks that don't take up a full block like doors, japanese walls, and probably others. Not every block that fits this category does this though
---------------------------------
Intended resolution:
1) figure out why players suffocate inside all blocks, most of which don't have `drowning = 1` (`> 0`). fix it. multicraft? 
2) figure out why setting `drowning = 1` for some blocks seems to affect the suffocation values of other blocks (e.g. doors). fix it. multicraft? 
3) make something like `real_suffocation` but which uses `damage_per_second`. otherwise, wearing `terumet:bracer_aqua` prevents players from dying while trying to glitch/hack through walls. 
4) insert something into `minetest.register_on_player_hpchange` to keep non-creative staff from dying in walls. add a priv check or something.

**Comment by fluxionary** [comment]
Suffocating in doors is fixed (though not live yet); perhaps some other things need checked.

**Comment by fluxionary** [comment]
Doors are fixed, but players still suffocate when standing near partial blocks; might have to implement a check on node type and exclude node box and mesh.

**Comment by fluxionary** [comment]
The door fix doesn't actually work on the server. I need to test things w/ local multicraft2. I've got access to that now, but I haven't gotten around to doing much w/ it.

**Comment by fluxionary** [comment]
Current update: 
real_suffocation is disabled. players still get suffocation bubbles whenever they stand partially inside a mesh/nodebox, but they don't take any damage.

**Comment by Lanhild** [comment]
I think you can't really do something with suffocation in microblocks, since it's from the hitbox of player and the hitbox of the microblocks block.

Though, Should this issue be closed?

**Comment by fluxionary** [comment]
It worked before multicraft. No-one knows why it doesn't work w/ multicraft on blocky. It works properly on other multicraft servers. Eventually, I hope to get around to looking into this more.

**Comment by luk3yx** [comment]
Blocky Survival has switched to MT 5.7, I assume it's no longer affected by this issue
