### ISSUE TITLE
titanium goggles: set daylight to 1

### ISSUE THREAD

**Issue by fluxionary** [obl3pplifp/BlS-issue-tracker#222]
this will make them work more like "night vision goggles", at least above ground. must make sure to make use of monoids.

**Comment by Lanhild** [comment]
Make the goggles execute the command /sunlight 1, so it makes your view appear as day, and when the goggles break or are removed, it execute /sunlight reset.

Don't know if it is what  you thinked, but it's what I thought you could do, if it's even possible.

**Comment by fluxionary** [comment]
i thought they already did that, let me check

**Comment by fluxionary** [comment]
they're supposed to, i suppose i need to test

**Comment by fluxionary** [comment]
it works, even in multicraft

**Comment by fluxionary** [comment]
oh lol this was my bug. i should have closed it ages ago
