### ISSUE TITLE
investigate why the name of the "game" blocky uses shows up as "Multicraft" instead of "minetest_game_modified"

### ISSUE THREAD

**Issue by fluxionary** [obl3pplifp/BlS-issue-tracker#229]
1. Set up a local tracker
2. Point my local multicraft2 instance at it
3. See what shows up when i use various games

relevant links:
https://github.com/minetest/master-server
https://github.com/minetest/master-server/blob/master/server.py#L350-L372

**Comment by luk3yx** [comment]
Has this been fixed?

**Comment by wsor4035** [comment]
![image](https://user-images.githubusercontent.com/24964441/97794147-8eeb5d80-1bcc-11eb-8442-4e6e51f4555c.png)
seems so

**Comment by fluxionary** [comment]
i thought it should read `minetest_game_modified`, but i'm ok w/ this.
