### ISSUE TITLE
Texture missing

### ISSUE THREAD

**Issue by fluxionary** [obl3pplifp/BlS-issue-tracker#231]
I get the following error sometimes:

```
ERROR[Main]: generateImage(): Could not load image "item_smoke.png" while building texture; Creating a dummy image
```

I can't see where it's being invoked through grep; I suspect BBQ.

**Comment by Lanhild** [comment]
I can't find from where it comes, I tested all the BBQ items and this error never pops

**Comment by fluxionary** [comment]
Perhaps not BBQ then. It's still happening, though rarely:
```
2020-10-19 15:39:45: ACTION[Server]: CHAT: <cb1> could not load image "item_smoke_png" :D
```

**Comment by Lanhild** [comment]
TechDude said:
`lanhildy, i should mention the item smoker texture missing is not from bbq, i got it from discovering lava`


This is the texture that is supposed to appear when you burn an item in lava.

So either the `item_smoke.png` has been erased, either it disappeared.

**Comment by fluxionary** [comment]
i did some deep searching through the mods and the game, and couldn't figure out what was causing this. 

i could just make `item_smoke.png` into a copy of bbq's smoke, and then the error would go away. any objections?

**Comment by Lanhild** [comment]
I think it's a good idea

**Comment by oversword** [comment]
The fake_fire chimneys and terumet also have smoke

**Comment by Lanhild** [comment]
logically fixed, the error doesn't appear anymore
