### ISSUE TITLE
Bed bugs 

### ISSUE THREAD

**Issue by krypticbit** [obl3pplifp/BlS-issue-tracker#236]
Somehow if you use a node replacer on a bed it can be duplicated.  Not to big of an issue because it's just beds.

**Comment by Lanhild** [comment]
I did not manage to reproduce it, so i couldn't test it, but I assume It can't be done inside protected areas?

**Comment by fluxionary** [comment]
The Negative Cheater
:
I suggest making beds unmoveable by mese
[
11:44 AM
]
The Negative Cheater
:
It makes a mess and can replace bedrock

**Comment by oversword** [comment]
I'm not seeing beds get duped, but I am seeing them as different items in the inventory, no stacking with the original
