### ISSUE TITLE
Live map of BlS server

### ISSUE THREAD

**Issue by Lanhild** [obl3pplifp/BlS-issue-tracker#241]
As we wanted a live map for BlS, I made my own research to help a bit (hope it helps)

    1. This forum topic explains the mod mapserver and it's features : 
    https://forum.minetest.net/viewtopic.php?f=14&t=21999&p=341825

    2. This Git link includes the whole documentation & the directions and configuration: 
    https://github.com/minetest-mapserver/mapserver/blob/master/readme.md

I tested it on my test server, and PandoraBox, works pretty smoothly.

Everything you need to know is explained in the links up :+1:

**Comment by Lanhild** [comment]
Here's a demo:

https://pandorabox.io/map/#!/map/0/6/-732/-844

**Comment by oversword** [comment]
yay http://mt.krypticbit.com:18785/#!/map
