### ISSUE TITLE
Unknown Item

### ISSUE THREAD

**Issue by TechDudie** [obl3pplifp/BlS-issue-tracker#244]
Today when I logged on, i decided to check my shop storage. then I found a Unknown Item.

**Comment by Lanhild** [comment]
Can you do /whatisthis and then report the result here?

**Comment by TechDudie** [comment]
okay, sure

**Comment by TechDudie** [comment]
its moremesecons_commandblock:commandblock_off (maybe a typo)

**Comment by Lanhild** [comment]
Was a More mesecons craftable command block

**Comment by TechDudie** [comment]
yep

**Comment by TechDudie** [comment]
i bought one 2 month ago

**Comment by fluxionary** [comment]
why was this closed

**Comment by fluxionary** [comment]
I disabled the moremesecons command block over security considerations. sorry about that. we can refund anyone's materials in exchange for the unknown nodes/items.
