### ISSUE TITLE
Terumet

### ISSUE THREAD

**Issue by TechDudie** [obl3pplifp/BlS-issue-tracker#245]
I decide to explore a month ago and i found a heatline distributer with an error when i opened its GUI

**Comment by TechDudie** [comment]
i not sure, but now i dont see an error

**Comment by fluxionary** [comment]
There's a known issue w/ a *really old* update, that caused the UIs of machines placed before the update to screw up a bit. The fix is to just break and re-place the machine. I think that was before this bug tracker was a thing, even.
