### ISSUE TITLE
ENHANCEMENT: food and no death bracer

### ISSUE THREAD

**Issue by TechDudie** [obl3pplifp/BlS-issue-tracker#247]
It would be nice to have a food and no death bracer, normally I’m going on long dangerous journeys and it would be nice to reassure myself that I won’t lose my armor because I won’t die of fall damage or hunger. Perhaps the no death bracer is made out of entropy matrix, and the hunger bracer is made out of coreglass blocks, and the hunger bracer loses a bit of durability when the hunger bar is zero, and then set it back to full hunger bar.

**Comment by ViniProTheBro** [comment]
i believe somthing like those bracers would very much be unbalanced just think about it never eating again would make all the food items basicly worth nothing and besides breaking that part of the econemy it would also take out probebly one of the main damage dealers of the game and i dont think the no death bracer would be any better. besides we already have vials of reviving if you realy dont want to die.

**Comment by TechDudie** [comment]
Well,the bracers will break after some time, say 10 times no eat, and 5 time die

**Comment by Lanhild** [comment]
It is a good idea, but not on BlS, because there are already the vial of reviving. It won't be worked on on this server at least. Also there is already vacuum packed food. The economy is mainly based on terumet selling and factory items.

**Comment by fluxionary** [comment]
I concur, this isn't a good idea and won't happen.
