### ISSUE TITLE
if you have a laggy client and dig beneath you, you might end up digging a hole even if it’s protected and you fall through

### ISSUE THREAD

**Issue by TechDudie** [obl3pplifp/BlS-issue-tracker#248]
Security: if you have a laggy client and dig beneath you, you might end up digging a hole even if it’s protected and you fall through. This happened to me on a about 6yr old somewhat cheap Samsung phone.

**Comment by TechDudie** [comment]
This won’t work on a 1yr old iPad with multicraft as the cilent, but if youre moving around a lot, you may fall through

**Comment by ViniProTheBro** [comment]
note to this: somthing simulair happend but i believe it is only client sided or so i was told

**Comment by TechDudie** [comment]
Perhaps, I haven’t checked that area in a while I’ll try to do it today

**Comment by TechDudie** [comment]
Either way, people can still go through the hole even if it is cilent sided, so people still can break into building roofs

**Comment by TechDudie** [comment]
Suppose it’s the roof to a honey farm, then people can raid the honey

**Comment by TechDudie** [comment]
If it’s cilent sided, should you have the broken item in your inventory?

**Comment by ViniProTheBro** [comment]
do you get the item then?

**Comment by TechDudie** [comment]
Yes

**Comment by TechDudie** [comment]
I should mention, I put might because you have to dig repeatedly for a while to break the block. This will happen, so there shouldn’t be a can’t confirm label

**Comment by fluxionary** [comment]
This is a long standing known issue w/ minetest that will never be fixed. If you want to keep people from digging in through your roof, use the wall-like highly protected nodes. 

(actually it may be fixable w/ SSCSM, but that's voluntary)
