### ISSUE TITLE
Smartshop

### ISSUE THREAD

**Issue by TechDudie** [obl3pplifp/BlS-issue-tracker#253]
This isn’t much of an issue, I’m not sure whether it’s worth working on or if you can fix it, but if the player’s inventory is full except for 1 item stack and you’ve already clicked on a item and are buying from a smart shop, maybe you should check if the payment item is the same as the price item before complaining no room in inventory, because if the payment item is the same and the quantity is the same, there isn’t any payment item leftover, so there still remains a item space empty for the bought item. (Sorry if I’m unclear.)

**Comment by TechDudie** [comment]
This is kinda annoying, in this situation I noticed that you can use the crafting grid as temporary storage at the expense of being able to craft things.

**Comment by fluxionary** [comment]
so.... you're saying that there's a very specific situation, in which the shop says "you can't perform this idempotent action", when you technically can? is there any benefit from fixing this other than satisfying OCD? the "can purchase" code is already rather complex, and fixing this is non-trivial. 

p.s.
you should report any further issues directly to my smartshop repo:
https://github.com/fluxionary/minetest-smartshop/issues

**Comment by TechDudie** [comment]
Well, your words are making my brain hurt ;) but ig yeah

**Comment by fluxionary** [comment]
okay, closing this then :)
