### ISSUE TITLE
tubelib & tnt

### ISSUE THREAD

**Issue by fluxionary** [obl3pplifp/BlS-issue-tracker#254]
```
PM from Oversword: it seems tnt will destroy tube but not break the connection
```

**Comment by oversword** [comment]
I think there's like an on_blast method or something that maybe hasn't been implemented, I might be able to fix this one

**Comment by oversword** [comment]
Yeah that's it, the easiest solution here is do make it invounerable to TNT, but I think I will try to make it do the same thing as on_dig

**Comment by oversword** [comment]
Fixed in https://github.com/joe7575/techpack/pull/58
