### ISSUE TITLE
Mod request: pager

### ISSUE THREAD

**Issue by Mathiaszero** [obl3pplifp/BlS-issue-tracker#255]
I think what would be really cool to have (and maybe for other players) in the server is a pager.  Essentially, the player creates a receiver block and places it next to a digiline or mesecon node and if the node is in on position, the receiver will light up.  The player can craft a pager to receive the information, like what real life pagers do. So when the receiver lights up, it will send a visual and/or auditory signal to the pager, even if the player was far away from the receiver.  I think it would be useful in situations where the player would like to keep track of the status of his/her factory, such as empty chest, activated node detector, entities piling, and other things. Also, logging might not be necessary since all messages are sent solely to the player who crafted the items, not to anyone else on the server (like messaging or reminding yourself), so any spam will not appear to others.  The messages can display in the default chat or in a custom part of the screen. Another feature is that you can add an ignore function so that a certain time has to pass before your pager will ding. My proposed recipe for the receiver would be a luacontroller and a stick, and for the pager it would be a noteblock and lcd.

Thanks in advance for considering my request.

**Comment by TechDudie** [comment]
Perhaps you can also send messages to other players, but they have to click a button on the GUI so they don’t get annoyed on purpose. For example, this might be useful when 2 people are running a store or a factory together.

**Comment by Lanhild** [comment]
There are ways to do that with existing in game items like Lua controller. Ask the players on the server for help.
