### ISSUE TITLE
More smartshop

### ISSUE THREAD

**Issue by TechDudie** [obl3pplifp/BlS-issue-tracker#256]
Now, I opened a smart shop, DIDNT buy anything, but it turned green, indicating that I supposedly bought something. Totally wrong.

**Comment by fluxionary** [comment]
They check the "send" storage when you open them. I'd bet there was something in there.

**Comment by oversword** [comment]
@TechDudie The green indicates that there is ~~stock~~ money in the storage, all you did was cause an update

**Comment by TechDudie** [comment]
Oh
