### ISSUE TITLE
Fix tubelib:harvester_base fuel slot

### ISSUE THREAD

**Issue by fluxionary** [obl3pplifp/BlS-issue-tracker#258]
Currently it lets you burn *absolutely anything* (though you have to load it w/ a pusher)

**Comment by oversword** [comment]
Also occurs with quarry. I'm looking into this, but no guarantees, tubelib bugs be tubelib bugging

**Comment by oversword** [comment]
I would like a solution that disallows non-fuel to be pushed into the slot, but I think first I'm going to make it so that only fuel burns since it should be easier. Ideally the final code would check both those boxes.

**Comment by oversword** [comment]
Fixed in this PR https://github.com/joe7575/techpack/pull/57
