### ISSUE TITLE
Cloaked players can be seen on minimap

### ISSUE THREAD

**Issue by Lanhild** [obl3pplifp/BlS-issue-tracker#261]
Title says everything :/

**Comment by luk3yx** [comment]
This is an engine limitation.

Relevant issues/PRs: https://github.com/minetest/minetest/issues/8316 https://github.com/minetest/minetest/pull/8397 https://github.com/minetest/minetest/pull/9863

**Comment by luk3yx** [comment]
This may eventually be fixed (in https://github.com/luk3yx/minetest-cloaking/commit/e5cf987c81a4ddb9e4e13a20bed07a115a517775), however this requires both server and client to be using 5.4.0-dev and could be easily bypassed by using 5.3.0 or earlier.

**Comment by luk3yx** [comment]
I don't think anything else can be done about this.
