### ISSUE TITLE
Terumet error

### ISSUE THREAD

**Issue by TechDudie** [obl3pplifp/BlS-issue-tracker#262]
I found the error while linking up headline for my factory. #245 
Teleport to 115=X,-10=Y,-5014=Z
Open the headline distributed and u get 
ERROR[Main]: Invalid Tooltip element(3) 0.0,1.5,1.1,Mese Garden 1 distance at (112,-10,x5015)
Or something like that.

**Comment by TechDudie** [comment]
Now I hooked up an expansion crusher and I get even more errors, but at least it works. :)

**Comment by TechDudie** [comment]
P.s. I did try breaking and placing the machine.

**Comment by fluxionary** [comment]
@TechDudie what client version are you using?

**Comment by TechDudie** [comment]
multicraft, I’ll check the version ltr, I’m kinda busy now

**Comment by TechDudie** [comment]
It says
Multicraft open source project ver. 1.14.0
Copyright (c) 2014-2020 multicraft development team
License LGPLv3.0+ and Cc-By-Sa-4.0
HOME PAGE: https://multicraft.world
Blah blah blah...

**Comment by fluxionary** [comment]
per luk3yx: 

```
MultiCraft 1 is based on MT 0.4 and doesn't have sized tooltips
```

try using an official minetest release (say, 5.2) if you can. nothing else we can do.

**Comment by TechDudie** [comment]
Okay but I’m on an iPad sometime and that’s the best cilent I can find, I guess I’ll just have to,deal with it. *sigh*
