### ISSUE TITLE
You can pull stuff from pchests, as well take stuff via the io upgrade in terumet.

### ISSUE THREAD

**Issue by TechDudie** [obl3pplifp/BlS-issue-tracker#267]
Himybro told me about the pushers, and I saw cadyn doing it with his pchests.

**Comment by TechDudie** [comment]
I saw issue #235, but pchests are more likely to contain valuble stuff. For example, mine contains a stack of mese and diamond ore, a stack of mycena mushrooms, and a stack of caverealms mese, as well as other things such as 2 backup antigravity bracers and 9 automatic gravel sieves.

**Comment by oversword** [comment]
This is not a bug. This is expected behavior, frankly I'm glad to hear it works this way, I might even start using this feature!

My recommendation would be to not leave your valuables laying around.

**Comment by TechDudie** [comment]
Well at least add a checkbox to the pchest interface to select if other machines can take stuff out of it.

**Comment by Lanhild** [comment]
Why? It's useless to add that. If you don't want stuff to be taken out of it, just don't put it near a pusher or anything that can take stuff out of the chest.
