### ISSUE TITLE
locked travelnets can't be updated

### ISSUE THREAD

**Issue by Lanhild** [obl3pplifp/BlS-issue-tracker#268]
^

**Comment by Lanhild** [comment]
Guess it comes from the fix that prevented from going into locked tnets

**Comment by TechDudie** [comment]
yep kinda annoying

**Comment by oversword** [comment]
This was intentional, not a bug. Other users should not be able to change your travelnets in any way.

**Comment by oversword** [comment]
@Lanhild where are you seeing this? My fix doesn't seem to be on the server yet

**Comment by Lanhild** [comment]
I guess I just got mixed up in my thoughts. Closing the issue rn
