### ISSUE TITLE
Skybox shows stars above 5000

### ISSUE THREAD

**Issue by oversword** [obl3pplifp/BlS-issue-tracker#276]
This conflicts with the skybox images up there, and also adds stars to "blackness", making it not black. I believe this goes against intended functionality

**Comment by oversword** [comment]
Fixed by https://github.com/BlockySurvival/other_worlds/pull/4

**Comment by oversword** [comment]
IDK why the checks have failed

**Comment by Lanhild** [comment]
it's the luacheck that always fails on this repo, not your fault normally
