### ISSUE TITLE
Add notify mod 

### ISSUE THREAD

**Issue by oversword** [obl3pplifp/BlS-issue-tracker#279]
I have written a mod that lets us more easily utilise the HUD for notifications, in the same way that the rhotator mod does, but with a few extra features.

This will let us standardise all notifications, displaying them in the same way, and not having to use chat to inform users of events

https://github.com/oversword/notify

**Comment by oversword** [comment]
https://github.com/BlockySurvival/bls_mods/pull/5

**Comment by luk3yx** [comment]
Do you have mods in mind that you plan to make use the notify API?

**Comment by oversword** [comment]
@luk3yx 

- The travelnet needs it, the notification is annoying and useless in chat
- Shops could also use it, the chat notifications are often missed by new players
- The notifications from the rhotator could also be replaced by this, as that is what this is based off of

Really anything that goes through `minetest.chat_send_player` should use this instead for consistency, as it's likely the chat was only used because they CBA to do it nicely - I can imagine some cases where we actually want to use the chat, but most things are better off in the hud
