### ISSUE TITLE
Make caverealms cobble types spread naturally

### ISSUE THREAD

**Issue by oversword** [obl3pplifp/BlS-issue-tracker#282]
We should allow the caverealms stone with moss/lichen to be collectable so it can be used for building

This should only be possible through the ore cutting saw so as to make it harder to do, keeping it rare

**Comment by fluxionary** [comment]
You can get it currently w/ the ore saw. adding the logic from caverealms_lite that allows it to spread to cobble, though, might be a good idea.

**Comment by fluxionary** [comment]
Though we could also do w/ a proper "silk touch" tool(set)

**Comment by oversword** [comment]
What about a full blown enchantment mod? We could ignore the terumet tools / armor to keep the count down and avoid making anything OP, so it's either magic or science, not both

Also, I did not realise you had already added this in, I should have checked, thanks

**Comment by oversword** [comment]
Confirmed this is working, I'll look into the caverealms_lite code.
I also think we could add some crafts? New that we have moss (Larch Moss [larch]) , purple mushrooms (Lentinus strigosus [nsspf]) and Alga (sp?) (Green Alga [aqua_farming])

**Comment by fluxionary** [comment]
Note that nsspf is totally inert rn, and that the nodes from it don't spawn or spread. I needed a way to keep them from growing in protected areas (also the ABMs were a bit too heavy), because it was really annoying to have mushrooms appearing on the sides of everyone's buildings. Also I think that lentinus obligately grows on trees. It'd make more sense to make use of the little purple caverealms mushrooms.

**Comment by oversword** [comment]
I wanted to sort that actually, I'll add an issue (https://github.com/BlockySurvival/issue-tracker/issues/287)
Ahh the caverealms:fungus? That does make more sense, IDK why I wouldn't just collect the blocks it grows on though :P

I thought you added nsspf returns to the sieve from dirt?

**Comment by fluxionary** [comment]
yup i did! but it'd be far better if they appeared in the wild again, somehow.

**Comment by fluxionary** [comment]
also, i only added the mycorrhizal or saprophytic mushrooms, not treebound parasites.

**Comment by oversword** [comment]
Arguably we and the plants are the parasites, but that is a discussion for a different forum ;)
