### ISSUE TITLE
Categories for the Unified Inventory

### ISSUE THREAD

**Issue by oversword** [obl3pplifp/BlS-issue-tracker#286]
I wanted to add categories for the unified inventory, which should make browsing our mods easier.

It's currently under review on the origin repo
https://github.com/minetest-mods/unified_inventory/pull/171
https://github.com/minetest-mods/unified_inventory/issues/170

This issue is to inform you guys about the functionality and maybe get you t test it out & review it.
After that is done & merged, this issue will also be used to keep track of the progress of categorising all our items, and coming up with categories

**Comment by oversword** [comment]
Proposed categories (in addition to existing ones):
- Food
- Automation
- Fungi
- Animals
- Armor
- Vehicles
- Decorations

Existing groups:
- Building
- Tools
- Plants
- Minerals
- Environment
- Lighting

Most other groups can be filtered by searching something specific

**Comment by Lanhild** [comment]
Categories as search filters or proper tabs in the UI ?

**Comment by oversword** [comment]
@Lanhild they will be like tabs, but tabs cannot contain images or be scrolled, so I had to do it with buttons

**Comment by Lanhild** [comment]
That's perfectly fine to me

**Comment by oversword** [comment]
Finally got this merged!
Will now make a PR to update unified_inventory, and will try to categorize all our items

**Comment by oversword** [comment]
We should set `unified_inventory_automatic_categorization = false` in `minetest.conf`, I would rather do it manually
