### ISSUE TITLE
Take ownership of the travelnet mod

### ISSUE THREAD

**Issue by oversword** [obl3pplifp/BlS-issue-tracker#288]
The travelnet mod (https://github.com/Sokomine/travelnet) is pretty horrible and deserves a re-write for its indentation alone

The code should be formatted

The Notification about how to use should be changed

A new "TARDIS" travelnet should be added that can teleport to any place randomly

**Comment by Lanhild** [comment]
> A new "TARDIS" travelnet should be added that can teleport to any place randomly

A command like `/tprandom` would be, I think, better and more practical to use. Though, it should not teleport into protected areas, and have a cooldown to use it.

**Comment by Lanhild** [comment]
Or instead of blocking teleporting into protected areas, a custom property added to areas could be done. Something similar to `/area_flak`

**Comment by oversword** [comment]
I would be happy to add that command but I think it'd be far more fun to have a TARDIS node, it would be able to teleport into protected areas but it'd be impossible to pick it up, and it would be uncraftable. There would be one on the server and the admins would each have a key they can use to call it to their location

**Comment by Lanhild** [comment]
I understand for the fun of the node. 
So it would be:
* Unbreakable, except with admin pick / WE
* Uncraftable (so give-able)
* For admins / mods / builders I think it would be better to have the command, instead of a key or something;
## (commands name probs won't be that) I would see it like this:
> `/tprand_set` to set the location of teleportation

> `/tprand` to teleport to the set location

**Comment by oversword** [comment]
Another thing: Travelnets could have multiple pages, lifting the connection limit

**Comment by BuckarooBanzay** [comment]
> Another thing: Travelnets could have multiple pages, lifting the connection limit

We started to rewrite/improve it here: https://github.com/mt-mods/travelnet
PR's, contributors and maintainers welcome 👍

**Comment by oversword** [comment]
@BuckarooBanzay 
> We started to rewrite/improve it here: https://github.com/mt-mods/travelnet
> PR's, contributors and maintainers welcome 👍

I literally just finished cleaning up the formatting myself, I'd probably rather redo it myself to be honest, I'm not sure everyone would want the features I do

**Comment by fluxionary** [comment]
@oversword 
not sure what your plans for features are, but i'd certainly jump at the chance to pick up all the bugfixes buckaroo has probably done. we could still fork, but maybe from his version.

**Comment by oversword** [comment]
@fluxionary plans for features are in this issue
I probably should to be honest... I'm not currently aware of any bugs though
Also looking at the diff I would still have to change every line to fix this damn formatting, it would be unmergable as soon as I make the first commit

**Comment by fluxionary** [comment]
ah. i wholeheartedly agree to fixing formatting if it's terrible :) i think i remember that from soko's mods, one of the reasons why i rarely stuck my head into them too deeply

**Comment by oversword** [comment]
Closed now we are using https://github.com/mt-mods/travelnet
Will make a new issue for making a tardis mod
