### ISSUE TITLE
Scifi nodes strong window panels are not transparent

### ISSUE THREAD

**Issue by akozlovskiy119** [obl3pplifp/BlS-issue-tracker#306]
When I play on the server, strong windows panels are not transparent. Although on a local installation with the same settings and latest version of scifi_nodes they are transparent.

Screenshot demonstrating the problem: left - server, right - local:
![Снимок экрана от 2021-06-12 00-27-51](https://user-images.githubusercontent.com/22382143/121750440-0e52ef00-cb15-11eb-9f6d-0d42a9df7031.png)

**Comment by oversword** [comment]
@akozlovskiy119 I cannot replicate this, can you show me on the server?

**Comment by akozlovskiy119** [comment]
I don't know what exactly has changed, but now they are transparent on the server. Sorry, I should have written this earlier.
