### ISSUE TITLE
Groups for meat an cheese

### ISSUE THREAD

**Issue by oversword** [obl3pplifp/BlS-issue-tracker#312]
Make groups for meat and cheese if they do not already exist, and make sure crafts use these groups if there is no reason to use a specific meat / cheese.
Specifically this has been requested for pepperoni and pepperoni pizza by MUD

MUD1
currently you can craft pepperoni using [any kind of meat] + chili paper
but you cant craft them using beef or raw beef.

and again instead of having so much recpies what about a group contains everymeat + chili peper

MUD1
there is duplicate rcipes for food from extra mod
example pepperoni pizza

MUD1
it was goat cheese but what about having a cheese group and make it group instead of two crafting recipes

**Comment by MihinMUD** [comment]
hi i am MUD

there is a meat group exist already, its from the mobs_animal mod.
but it does not contain raw beef or cooked one because thats from bbq mod.
maybe if added raw beef and beef in to it, and add it to recipes, it will be so easy to get the needed recipe

**Comment by oversword** [comment]
Not fixed cheese group or "there is duplicate rcipes for food from extra mod"
