### ISSUE TITLE
High Performance Pusher Not Moving Stacks

### ISSUE THREAD

**Issue by Brackston** [obl3pplifp/BlS-issue-tracker#358]
I noticed that the High Performance(HP) Pusher does not move stacks like the HP distributor does, The Fast Pusher is faster than the HP Pusher since the HP Pusher slowly moves one item at a time like a normal pusher.

**Comment by oversword** [comment]
The high performance pusher will only move entire stacks out of a high performance chest, some of the other tubelib machines, and the portable chest.

It does work, just not on everything, I would recommend trial and error to find out which inputs it will work with - or, if you're partial to a bit of code, you may want to try and find the machine in the code and figure out what it does from that https://github.com/BlockySurvival/techpack . If the machine isn't in there try and figure out what mod it's from and look it up in our list of all installed mods https://github.com/BlockySurvival/bls_mods

**Comment by Brackston** [comment]
Thank you for the links, I will check it out when I have time...currently busy with RL, church, and Blocky survival :)
