### ISSUE TITLE
Ongoing DOS against all servers

### ISSUE THREAD

**Issue by fluxionary** [obl3pplifp/BlS-issue-tracker#378]
Due to the https://github.com/minetest/minetest/issues/11877, it is currently trivial for a hacker to crash a minetest server, and the makeworld hacker is using it to DOS the entire community.

**Comment by fluxionary** [comment]
So far, blocked 3 ASNs for a year (A46562, A31343, A43350)

**Comment by luk3yx** [comment]
I've migrated Blocky Survival's auth database to LevelDB for now to try and work around the problem.

**Comment by fluxionary** [comment]
closing this as no longer relevant; the MakeWorlds guy seems to have gotten bored, and the engine issue got fixed.
