### ISSUE TITLE
2 different silicon lumps.

### ISSUE THREAD

**Issue by JohannesPaulHoffmann** [obl3pplifp/BlS-issue-tracker#380]
Hi,

We have now Silicon Lump and Silicon.

Several thin's can't be crafted anymore.

Thanks for lookin' into it!

Regards,
Johannes

**Comment by fluxionary** [comment]
if i remember, this is an "emergent" bug that depends on the order that certain mods load. aliasing the silicon is pretty trivial though.

**Comment by oversword** [comment]
It's because mesecons was updated and seems to provide its own now, will alias

**Comment by oversword** [comment]
Can't tell if it did before? We seem to have them both in the microblocks cleanup... Anyways, its fixed
