### ISSUE TITLE
Walrus can't be fed (therefore not tamed).

### ISSUE THREAD

**Issue by JohannesPaulHoffmann** [obl3pplifp/BlS-issue-tracker#381]
Hello,

the walrus does follow the Clownfish, the Tropical fish and the Penguin, but can't be fed with Them.

Thanks, for lookin' into this issue!

Regards,
Johannes

**Comment by fluxionary** [comment]
i'm pretty sure the walruses were not intended to be tamable.

**Comment by oversword** [comment]
Yeah I think the behaviour is actually hostile: they actively hunt penguins and fish themselves

**Comment by JohannesPaulHoffmann** [comment]
Good evenin',

Walrus' still can't be fed with Fishs or Penguins.

But follows the 3 food types, if I hold Them.

Placed the Penguin & the Fishs, but the Walrus doesn't start to hunt Them.

Regards,
Johannes
