### ISSUE TITLE
Robot loops command.

### ISSUE THREAD

**Issue by JohannesPaulHoffmann** [obl3pplifp/BlS-issue-tracker#387]
I saw, that robot.move() shall move the robot one node forwards, but it keeps on loopin', than:

robot.move()
robot.turn()

issues: 'can only perform one action at a time'.

**Comment by oversword** [comment]
```
mem.step = mem.step or 0

if mem.step % 2 == 0 then
  robot.move()
else
  robot.turn()
end

mem.step = mem.step + 1
```
