### ISSUE TITLE
Please update 3d_armor mod

### ISSUE THREAD

**Issue by akozlovskiy119** [obl3pplifp/BlS-issue-tracker#403]
The master branch of `3d_armor` mod from `minetest_mods` contains many fixes, one of them is related to the fact that the old version incorrectly handled right-clicking an armor item by forgetting to call the `on_equip` callback in the `armor.equip` function (same with `armor.unequip` and `on_unequip`).

An example of this incorrect behavior on BlockySurvival is the night vision goggles from the `titanium` mod, which don't work when equipped by right-clicking.

**Comment by luk3yx** [comment]
I've updated 3d_armor, the new fixes should appear the next time the server reboots.
