### ISSUE TITLE
Update locked_travelnet in the server

### ISSUE THREAD

**Issue by sfiedler0** [obl3pplifp/BlS-issue-tracker#404]
It seems like in BlockySurvival, when we delete a shared locked travelnet, the upper node (or vector) is still contained. However, I downloaded the referenced locked_travelnet from [mt-historical/locked_travelnet](https://github.com/mt-historical/locked_travelnet) and locally, it seems to work perfectly. Also, the reference in this repo is up-to-date with `master` of `mt-historical/locked-travelnet`.  
Because of this I think the locked_travelnet in the server *itself* is not up-to-date (maybe forgot a git submodule update), so it would be great if this repository part (locked_travelnet) would get updated on the BlockySurvival server.

**Comment by luk3yx** [comment]
The version of locked_travelnet on the server appears to be the latest version in the locked_travelnet repo, perhaps it has something to do with the version of the travelnet mod used or maybe some other mod on BlS?

**Comment by sfiedler0** [comment]
Please apologize for my wrong information. I just found out that the regular locked_travelnet contained this bug. This must have been a failure in my testing...  
I will open a pull request in `mt-historical/locked_travelnet` with my updated version.
