### ISSUE TITLE
Add feature to unified inventory to cycle through conflicting recipes

### ISSUE THREAD

**Issue by fluxionary** [obl3pplifp/BlS-issue-tracker#82]
This was a feature request on unified inventory a few years ago (https://github.com/minetest-mods/unified_inventory/issues/54) but they declined to implement it. If someone submitted a functional PR, though, they might incorporate it.

**Comment by oversword** [comment]
I think I would prefer to fix the conflicts, as per https://github.com/BlockySurvival/issue-tracker/issues/341

This would certainly be a good feature if someone were to re-do the crafting guide entirely

I was also thinking of having the ability to filter crafts depending on if you have the required items in your inventory
I would also like something that has a better ability to add "modules" from external mods

I'll write all of this up in its own issue

https://github.com/BlockySurvival/issue-tracker/issues/373
